### ISSUE TITLE
The algorithm gets lost in deep functions

### ISSUE THREAD

**Issue by GBertholon** [Sakarah/GeneTipe#7]
Often when you test the program with the standard depth, it does not converge toward a solution because the population quickly get too much complex before having an approximate solution.
How could we solve that ?

**Comment by Gabzcr** [comment]
We could create another way of evaluating fitness which would slightly decrease the fitness of deep functions so that the algorithm would choose the simplest solution between two identical ones (considering fitness). Also depending on how we penalize deep functions, this could filter noise in experimental measures or even simplify a problem by making an approximation with a simpler function.

**Comment by GBertholon** [comment]
We should look to "Dynamic limits for bloat control in genetic programming and a review of past and current bloat theories" in order to solve this problem.

**Comment by GBertholon** [comment]
Taking size into account in fitness is enough to avoid this problem. This is what I do in regexp-search with the multi-objective fitness evaluator.
